all:
  vars:
    # ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q root@10.16.231.155"'
  children:
    cnfde7:
      children:
        installer:
          hosts: 10.16.231.155
        ptp:
          hosts:
            # cnfde7.ptp.lab.eng.bos.redhat.com:
            cnfde4.ptp.lab.eng.bos.redhat.com:
          vars:
            ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q root@10.16.231.155"'

